package it.uniroma1.mdp.controller;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import it.uniroma1.mdp.model.ModalityGame;

/**
 * This class handles the action event generated by selecting the "Full Game" mode in a JComboBox.
 */
public class FullGameModalityHandler implements ActionListener {

	private JComboBox<String> comboBox;
	
	 /**
     * Constructor of the FullGameModalityHandler class.
     */
	public FullGameModalityHandler(JComboBox<String> comboBox) {
		this.comboBox = comboBox;
	}
	
	/**
	 * Handles the selection of the "Full Game" mode in the JComboBox.
	 * Displays a warning message if "Full Game" mode is selected, resets the JComboBox index,
	 * and triggers the action to return to the main menu.
	 */
	@Override
	public void actionPerformed(ActionEvent e) {

		// 1. Saving the selected Item
		String selectedItem = (String)this.comboBox.getSelectedItem();
		
		// 2. If 'Full Game' has been selected
		if ( selectedItem.equals(ModalityGame.FULL_GAME.getValue()) ){
			// playing the sound
			AudioManagerController.getEffectAudioManagerInstance().playAlert();
			
			// 2.1. Showing the warning
			JOptionPane.showMessageDialog(null, "'Full Game' mode is not yet implemented.\nPlease, select 'Single Game' mode to play",
					"WARNING", JOptionPane.WARNING_MESSAGE);
			
			// 2.2. Making the index of the combo box from the start
			this.comboBox.setSelectedIndex(0);
			
			// 2.3. Going back to the main menu
			BackButtonHandler backHandler = new BackButtonHandler();
			ActionEvent backToMainMenuEvent = new ActionEvent(this, ActionEvent.ACTION_PERFORMED, "Back To the Main Menu");
			backHandler.actionPerformed(backToMainMenuEvent);
		}
		
	}
}
